### ISSUE TITLE
FileNotFoundException on Startup

### ISSUE THREAD

**Issue by FreeBird416** [iamvishnu-media/Apex-Launcher#31]
# Exception Details
System.IO.FileNotFoundException: Could not find file 'C:\Users\djhes\Downloads\Versions\VersionManifest.xml'.
File name: 'C:\Users\djhes\Downloads\Versions\VersionManifest.xml'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cachePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.OpenUrlDelegate(Object xmlResolver)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.CompressedStack.Run(CompressedStack compressedStack, ContextCallback callback, Object state)
   at System.Xml.XmlTextReaderImpl.OpenUrl()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Apex_Launcher.VersionGameFiles.GetAllVersions()
   at Apex_Launcher.VersionGameFiles.FromString(String str)
   at Apex_Launcher.Program.Initialize()
   at Apex_Launcher.Program.Main()

# Configuration
* Current Launcher Version: 1.6.0.0
* Current Game Version: 
* Install Path: C:\Users\djhes\Downloads

# Files
* `config.txt`
* C:\Users\djhes\Downloads:

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment]
Thanks for reporting. I should be able to add a workaround for this for the next version.

**Comment by iamvishnu-media** [comment]
This issue should be fixed and will be patched in the next release.

**Comment by iamvishnu-media** [comment]
Fixed in version 1.6.1
