### ISSUE TITLE
DirectoryNotFoundException in WinIOError

### ISSUE THREAD

**Issue by MartelloX** [iamvishnu-media/Apex-Launcher#35]
# Exception Details
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Owner\Downloads\Versions\ALPHA 9'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.6.1.0
* Current Game Version: ALPHA 9p
* Install Path: C:\Users\Owner\Downloads

# Files
* `config.txt`
* C:\Users\Owner\Downloads:
    * C:\Users\Owner\Downloads\Versions:
        * `Game.rgssad`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by MartelloX** [comment]
not sure what this is tried downloading the new version through the launcher and this happened twice

**Comment by efnikolas** [comment]
Had the same issue because of a false positive of my AV. Program was trying to delete an old version file from desktop and AV thought it was malicious.

**Comment by iamvishnu-media** [comment]
Thanks, @efnikolas. @MartelloX can you try checking your antivirus to see if it's trying to quarantine the download folders?

**Comment by MartelloX** [comment]
I am positive thats what it is becuase ibhad to fight the antivirus just to
download the launcher in the first place I will fix the problem woth my
antivirus thanks for the help!

**Comment by iamvishnu-media** [comment]
No problem! I'll close this issue and add a warning to the readme about antivirus stuff.

**Comment by MartelloX** [comment]
Awsome thanks!
