### ISSUE TITLE
DirectoryNotFoundException in WinIOError

### ISSUE THREAD

**Issue by Xsoulibur** [iamvishnu-media/Apex-Launcher#36]
# Exception Details
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\PK Apex\Versions\Audio v1'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at ApexLauncher.DownloadForm.RecursiveCopy(String sourceDirectory, String destinationDirectory, Boolean overwriteFile)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.6.1.0
* Current Game Version: ALPHA 9.1p
* Install Path: C:\PK Apex

# Files
* `config.txt`
* C:\PK Apex:
    * C:\PK Apex\Versions:
        * C:\PK Apex\Versions\ALPHA 8
        * C:\PK Apex\Versions\ALPHA 8
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\PK Apex\Versions:
        * C:\PK Apex\Versions\ALPHA 8.1p
        * C:\PK Apex\Versions\ALPHA 8.1p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\PK Apex\Versions:
        * C:\PK Apex\Versions\ALPHA 8.2p
        * C:\PK Apex\Versions\ALPHA 8.2p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\PK Apex\Versions:
        * C:\PK Apex\Versions\ALPHA 9
        * C:\PK Apex\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\PK Apex\Versions:
        * C:\PK Apex\Versions\ALPHA 9.1p
        * C:\PK Apex\Versions\ALPHA 9.1p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\PK Apex\Versions:
        * C:\PK Apex\Versions\ALPHA 9.2p
        * C:\PK Apex\Versions\ALPHA 9.2p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

**Comment by iamvishnu-media** [comment]
This is interesting. Just to confirm, did you accept or decline the audio download?

**Comment by iamvishnu-media** [comment]
You may also want to check your antivirus settings as per #35 to see if the audio download got quarantined.

**Comment by reneplonus** [comment]
I was asked to install the Audio V1 only after I declined to install the latest build, maybe that alreafy fixes your problem (reject update - download audio v1 - restart launcher - accept update).
However, I was not able to download audio v1 and therefore opened [https://github.com/iamvishnu-media/Apex-Launcher/issues/37](url) (as far as I can tell my windows defender did not reject anything).

**Comment by reneplonus** [comment]
I was asked to install the Audio V1 only after I declined to install the latest build, maybe that already fixes your problem (reject update - download audio v1 - restart launcher - accept update).
However, I was not able to download audio v1 and therefore opened [](https://github.com/iamvishnu-media/Apex-Launcher/issues/37#issue-761303923) (as far as I can tell my windows defender did not reject anything).

**Comment by Xsoulibur** [comment]
**> This is interesting. Just to confirm, did you accept or decline the audio download?**
It didn't appeared at all, so i decided to download it manually, after seen the last comment. After that, I unzipped the file in the needed location, rename it as 'Audio v1' , and ran the launch again. With this done, it completed the update.

As a sidenote, the build said Alpha 9.3 in the launcher, but in the game selection it says Alpha 9.1.

**Comment by iamvishnu-media** [comment]
So could you give me a step-by-step of what happened? I'm a little unclear on exactly how this went down.

**Comment by Xsoulibur** [comment]
OK. This is more or less what happened.:

1. While running the Launcher it asked to update the game to the latest version which was 9.2 at the time.
2. After finishing the download it automatically went to installation.
3. During installation a window opened with the message error which i used the make the report. The installation never ended after closing the window with the error.
4. Days later i tried again, and this time the version was 9.3, but i got the same result.
5. After seen the comment made by **reneplonus**, i proceed to manually download the Audio v1 file from the site, but the name of it appeared as Audio on my PC after download.
6. Unzipped the file in the location that the error said it didn't found the path.
7. Renamed the unzipped file to Audio v1 to match the path name mentioned in the message of the report.
8. Closed the Launcher and proceed to run it again.
9. Accepted the version update request for the game.
10. It finished the download and installation process without any issues.

NOTE.: During all this time, it never asked to install the Audio v1 like it happened with **reneplonus**.
