### ISSUE TITLE
NullReferenceException when attempting to update Audio version

### ISSUE THREAD

**Issue by jBosh0404** [iamvishnu-media/Apex-Launcher#43]
When I open the apex launcher, a dialog box pops up asking if I want to update to the latest audio version, Audio v1. If I click "Yes" to update the audio, Apex Launcher throws an unhandled exception error. If I click "Continue" on the error message box, the launcher remains in a state of "checking for new versions" and doesn't let me launch the game. I have to select "no" from the audio update dialog box to be able to launch the game. I have included screenshots showing the update popup, the error message popup, and the launcher stuck searching for new versions. Additionally, the full text of the error is listed below:

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ApexLauncher.Program.DownloadVersion(IDownloadable v)
   at ApexLauncher.Program.InstallLatestVersion()
   at ApexLauncher.Launcher.Launcher_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Form.CallShownEvent()
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
Apex Launcher
    Assembly Version: 1.7.0.0
    Win32 Version: 1.7.0.0
    CodeBase: file:///C:/Users/JMess/Desktop/Pokemon%20Apex/Apex.Launcher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4330.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

![ApexLauncher_Audio_Update](https://user-images.githubusercontent.com/13006696/123803135-a1c84600-d8b1-11eb-841c-0a6e208140a7.PNG)
![ApexLauncher_Stuck_Searching_for_New_Versions](https://user-images.githubusercontent.com/13006696/123803140-a1c84600-d8b1-11eb-9b47-c46c52d47c16.PNG)
![ApexLauncher_Audio_Error](https://user-images.githubusercontent.com/13006696/123803142-a260dc80-d8b1-11eb-939f-ca6818da1b78.PNG)

**Comment by iamvishnu-media** [comment]
Thanks for reporting! I'll investigate this.

**Comment by iamvishnu-media** [comment]
Okay so it looks like the the only way I can think of that the `DownloadVersion()` method would throw a NRE is if it's specifically being instructed to queue up a `VersionAudio` class instead of a `VersionGameFiles`. I've added a bit of handling for that, so if the argument for that method is a `VersionAudio` instead, it will just ignore the embedded audio version checking.

I've attached a compiled version of the code with these changes. Could you test this out and see if this resolves this issue?
[Apex Launcher.zip](https://github.com/iamvishnu-media/Apex-Launcher/files/6734229/Apex.Launcher.zip)

**Comment by jBosh0404** [comment]
Well, it's doing something _different_ now... seems to be complaining about access to the Audio v1.zip file being denied. Would I need to run the launcher with Admin privileges? Stack trace is listed below, with a screenshot below that.

# Exception Details
System.UnauthorizedAccessException: Access to the path 'C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1.zip' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode)
   at ApexLauncher.DownloadForm.Download()

# Configuration
* Current Launcher Version: 1.7.0.0
* Current Game Version: ALPHA 9.3p
* Install Path: C:\Users\JMess\Desktop\Pokemon Apex

# Files
* `config.txt`
* C:\Users\JMess\Desktop\Pokemon Apex:
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 7.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.1p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 8.2p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\ALPHA 9.3p
        * `Game.exe`
        * `Game.ini`
        * `Game.rgssad`
        * `gif.dll`
        * `RGSS102E.dll`
        * `RGSS104E.dll`
        * `rgssdisp.dll`
        * `rubyscreen.dll`
    * C:\Users\JMess\Desktop\Pokemon Apex\Versions:
        * C:\Users\JMess\Desktop\Pokemon Apex\Versions\Audio v1

# Environment
* Locale: en-US
* Operating System: Microsoft Windows NT 6.2.9200.0
* .NET Runtime Version: 4.0.30319.42000

![ApexLauncher_Unauthorized_Access_Error](https://user-images.githubusercontent.com/13006696/123883253-46787100-d90e-11eb-967a-b2afdae97b3d.PNG)

**Comment by jBosh0404** [comment]
what I'm not understanding is that it seems to be referencing a ZIP that doesn't exist? Like it's trying to do something with the ZIP before it's been downloaded?

**Comment by jBosh0404** [comment]
I tried running the launcher EXE with Admin privileges, but it gives the same error. I thought maybe it was saying it doesn't have access to that filepath because it's trying to create the ZIP file, but running with Admin privileges would have given it access, or so I understand. I'll stop tinkering and leave the digging to you since you know what you're doing.

**Comment by jBosh0404** [comment]
I don't know if this is related in any way, but I've noticed a discrepancy between the build version listed on the Launcher vs the build version listed on the "load" screen when starting the game. The Launcher shows 9.3 but the game displays 9.1. Screenshots below.

Apex Launcher Build Version

![ApexLauncher_Build_Discrepancy](https://user-images.githubusercontent.com/13006696/123892024-695f5100-d91f-11eb-928f-39321ac832a3.PNG)

Apex Game Build Version

![ApexGame_Build_Discrepancy](https://user-images.githubusercontent.com/13006696/123892130-9c094980-d91f-11eb-9b79-537ba9c84261.PNG)

**Comment by iamvishnu-media** [comment]
The build number in the game is wrong because I forgot to update it. It's unrelated.

For the file access error, I would recommend trying again. Sometimes the file system doesn't want to let go of the .zip before the program is ready to access it. I'll probably have to add some wait time for that later.

**Comment by jBosh0404** [comment]
I've tried multiple times. Each time has had the same result. I'm not overly concerned about not having up-to-date audio, however. I can still play the game. I just dismiss the update query.

**Comment by iamvishnu-media** [comment]
The fact that it's occurring every time is actually a good thing, it means that it's reproducible. I'll take a look and see what I can figure out. In the meantime, double check your antivirus settings (including Windows Defender) to make sure the download isn't getting snagged by that.
